name: Local
variables:
  - name: authUrl
    value: https://localhost:8080
  - name: apiUrl
    value: http://localhost:5062
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJueTVxbHhFVGVzd2xobXBkTlFFb1M4MmlnVTVNY2NpOUl4ZUU1VC1UWklJIn0.eyJleHAiOjE3ODM3MjQxMjYsImlhdCI6MTc4MzcyMzIyNiwianRpIjoib25ydHJvOjBkYjdkZGI4LWQ5MzctMDU1Ni01MWU1LTMxMzJiOGM1YjRjNiIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL2FzcGlyZS1ndWlkZSIsImF1ZCI6InNhbXBsZS1hcGkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzYW1wbGUtYXBpLXVpIiwic2lkIjoiT1BFODRfR0lhVGE1bzFvRHU3T0QtczNiIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImFwaS1yZWFkZXIiXX0sInNjb3BlIjoiIn0.UZ033OQkPe0LSjr5jY2C-8vwkxFDs548BqL9LV1GwgKNpE62Q71tA77rO0BgTkF4i5kJlTdFykDIf4OZE1I573bz9WngXXUV6NEZXmufKGwbGD312e7Tv1Q82t9Mk9jV4jbuLhdBSIkoqRUmwbW-5VNbprumyDHNoRvrDviG0PYnGskCoyiyzbqkhza2GEoAI2qm6iA6abhUXQ2MuXpuAVdwRGnLMU-iNmNH6ZhxTdI4QYhl3I0X9WfcTO8nnkOw1WxeWqHsKtVnCEcBd3J1HDIRMBJVQbWaUDES4tHkv0V76ZlUYRmzKQExL0rptu-ZSgV8dR2tOEgC6Tvw2bO1Rg
